Fix TopologyPreservingSimplifier to remove ring endpoints safely
libgeos/geos pull request #1110
Opened 2024-06-13 22:48 UTC by dr-jts

Fixes `TopologyPreservingSimplifier` to remove ring endpoints safely, by ensuring that discarded line segments are removed from spatial indexes, and modified line segments are reindexed.

Fixes #1107.

2024-06-13 22:51 UTC, pramsey commented
Is it possible to add the triggering test case into one of the unit tests, so we get that sweet ASAN/valgrind automation from the CI on that code path?

2024-06-13 22:58 UTC, dr-jts commented
> Is it possible to add the triggering test case into one of the unit tests?

Yes, would be nice.  Maybe can slim the failure case down a bit.

2024-06-14 11:18 UTC, dbaston requested changes

2024-06-14 11:18 UTC, dbaston commented on src/simplify/TaggedLineString.cpp
> +TaggedLineSegment*
```suggestion
const TaggedLineSegment*
```

2024-06-14 11:18 UTC, dbaston commented on src/simplify/TaggedLineStringSimplifier.cpp
> +            TaggedLineSegment* flatSeg = line->removeRingEndpoint();
```suggestion
            const TaggedLineSegment* flatSeg = line->removeRingEndpoint();
```

2024-06-14 11:18 UTC, dbaston commented on include/geos/simplify/TaggedLineString.h
> +    TaggedLineSegment* removeRingEndpoint();
```suggestion
    const TaggedLineSegment* removeRingEndpoint();
```

2024-06-14 11:18 UTC, dbaston commented on include/geos/simplify/TaggedLineString.h
> +    TaggedLineSegment* removeRingEndpoint();
returning a `const` pointer here makes it clear that the caller does not own the returned object.

2024-06-14 16:44 UTC, dbaston approved these changes

2024-06-14 16:58 UTC, merged

2024-08-02 04:07 UTC, eglaser77 commented
Is this the issue referred to in the 3.12.0 release notes as "GEOSIntersects: Fix crash with empty point inputs (#1110, Dan Baston)" listed here: https://github.com/libgeos/geos/blob/3.12.2/NEWS.md#changes-in-3120? That description doesn't seem to match.

2024-08-02 14:04 UTC, dbaston commented
The issue referenced in the 3.12.0 release notes is Trac ticket 1110: https://trac.osgeo.org/geos/ticket/1110